[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

[target.armv7-unknown-linux-musleabihf]
linker = "arm-linux-gnueabihf-gcc"

[target.arm-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

[target.arm-unknown-linux-musleabihf]
linker = "arm-linux-gnueabihf-gcc"

[target.mipsel-unknown-linux-gnu]
linker = "mipsel-linux-gnu-gcc"

[target.mipsel-unknown-linux-musl]
linker = "mipsel-linux-musl-gcc"

[target.mips64el-unknown-linux-gnuabi64]
linker = "mips64el-linux-gnuabi64-gcc"

[target.mips64el-unknown-linux-muslabi64]
linker = "mips64el-linux-muslabi64-gcc"

[target.riscv64gc-unknown-linux-gnu]
linker = "riscv64-linux-gnu-gcc"

[target.s390x-unknown-linux-gnu]
linker = "s390x-linux-gnu-gcc"

[target.i686-win7-windows-gnu]
linker = "i686-w64-mingw32-gcc"
ar = "i686-w64-mingw32-ar"

[env]
CC_i686_win7_windows_gnu = "i686-w64-mingw32-gcc"
CXX_i686_win7_windows_gnu = "i686-w64-mingw32-g++"
AR_i686_win7_windows_gnu = "i686-w64-mingw32-ar
