[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

[target.armv7-unknown-linux-musleabihf]
linker = "arm-linux-gnueabihf-gcc"

[target.arm-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

[target.arm-unknown-linux-musleabihf]
linker = "arm-linux-gnueabihf-gcc"

[target.mipsel-unknown-linux-gnu]
linker = "mipsel-linux-gnu-gcc"

[target.mipsel-unknown-linux-musl]
linker = "mipsel-linux-musl-gcc"

[target.mips64el-unknown-linux-gnuabi64]
linker = "mips64el-linux-gnuabi64-gcc"

[target.mips64el-unknown-linux-muslabi64]
linker = "mips64el-linux-muslabi64-gcc"

[target.riscv64gc-unknown-linux-gnu]
linker = "riscv64-linux-gnu-gcc"

[target.s390x-unknown-linux-gnu]
linker = "s390x-linux-gnu-gcc"
