[target.armv7-unknown-linux-gnueabihf]
image = "ghcr.io/cross-rs/armv7-unknown-linux-gnueabihf:main"

[target.armv7-unknown-linux-musleabihf]
image = "ghcr.io/cross-rs/armv7-unknown-linux-musleabihf:main"

[target.arm-unknown-linux-gnueabihf]
image = "ghcr.io/cross-rs/arm-unknown-linux-gnueabihf:main"

[target.arm-unknown-linux-musleabihf]
image = "ghcr.io/cross-rs/arm-unknown-linux-musleabihf:main"

[target.s390x-unknown-linux-gnu-cross]
image = "ghcr.io/cross-rs/s390x-unknown-linux-gnu-cross:main"
