[target.armv7-unknown-linux-gnueabihf]
image = "ghcr.io/cross-rs/armv7-unknown-linux-gnueabihf:main"

[target.armv7-unknown-linux-musleabihf]
image = "ghcr.io/cross-rs/armv7-unknown-linux-musleabihf:main"

[target.arm-unknown-linux-gnueabihf]
image = "ghcr.io/cross-rs/arm-unknown-linux-gnueabihf:main"

[target.arm-unknown-linux-musleabihf]
image = "ghcr.io/cross-rs/arm-unknown-linux-musleabihf:main"

[target.s390x-unknown-linux-gnu-cross]
image = "ghcr.io/cross-rs/s390x-unknown-linux-gnu-cross:main"

[target.x86_64-unknown-netbsd]
image = "ghcr.io/cross-rs/x86_64-unknown-netbsd:main"

[target.x86_64-unknown-freebsd]
image = "ghcr.io/cross-rs/x86_64-unknown-freebsd:main"

[target.x86_64-pc-solaris]
image = "ghcr.io/cross-rs/x86_64-pc-solaris:main"

[target.x86_64-unknown-illumos]
image = "ghcr.io/cross-rs/x86_64-unknown-illumos:main"

[target.powerpc64le-unknown-linux-gnu]
image = "ghcr.io/cross-rs/powerpc64le-unknown-linux-gnu:main"
